apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
    - port: 4200
  type: LoadBalancer
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: admin
          ports:
            - containerPort: 4200
