apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 7001
  type: LoadBalancer
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend
          ports:
            - containerPort: 7001
