apiVersion: v1
kind: Service
metadata:
  name: coach
spec:
  ports:
    - port: 4201
  type: LoadBalancer
  selector:
    app: coach
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coach
spec:
  selector:
    matchLabels:
      app: coach
  template:
    metadata:
      labels:
        app: coach
    spec:
      containers:
        - name: coach
          image: coach
          ports:
            - containerPort: 4201
