apiVersion: v1
kind: Service
metadata:
  name: org
spec:
  ports:
    - port: 4202
  type: LoadBalancer
  selector:
    app: org
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org
spec:
  selector:
    matchLabels:
      app: org
  template:
    metadata:
      labels:
        app: org
    spec:
      containers:
        - name: org
          image: org
          ports:
            - containerPort: 4202
