// Generated by https://quicktype.io

export interface Coach {
  _id: string;
  avatar: string;
  name: string;
  email: string;
  mobile: string;
  gender: string;
  status: boolean;
  __v: number;
}
